### ISSUE TITLE
Crashing when loading any channel.

### ISSUE THREAD

**Issue by HimitsuYami** [Huderon/BetterDiscordPlugins#3] opened 2024-04-19 20:53 UTC
This plugin is crashing me whenever I try to load into any channel. According to the Crash Recovery plugin I'm using, I should tell you this:
[discord.com-1713559786216.log](https://github.com/Huderon/BetterDiscordPlugins/files/15045527/discord.com-1713559786216.log)

I have no idea what any of this means, but I do know that disabling this plugin stopped my crashing, turning it back on caused me to crash again.

**Comment by Huderon** [comment] 2024-04-20 02:58
Duplicate of #2

**Closed as completed** 2024-04-20 02:59 UTC
Labels: duplicate
